#!/usr/bin/env python3
"""Generate the hub's cross-boundary contract artifacts from the canonical source.

Single source of truth: the pydantic models in `state_aggregator.types`. This script
derives everything else so there is no hand-maintained duplicate:

  1. schema/snapshot.schema.json  <- pydantic `FleetState.model_json_schema()`
  2. ts/snapshot.ts               <- json-schema-to-typescript over (1)

Run from anywhere:  `python3 packages/hub-contracts/codegen.py`
(uses the repo's installed `state_aggregator`; runs `json2ts` from node_modules if present).

The checked-in artifacts are validated against this generator by the drift-guard test
(`state-aggregator/tests/test_hub_contracts_drift.py`): if pydantic changes and codegen
is not re-run, CI fails. That is the guard Codex #4 asked for.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCHEMA_PATH = HERE / "schema" / "snapshot.schema.json"
TS_PATH = HERE / "ts" / "snapshot.ts"
# Hand-authored schemas (external standards, not pydantic-generated) we still emit TS for.
HANDWRITTEN_SCHEMAS = [HERE / "schema" / "admiral-chat.schema.json"]


def _prune_property_titles(schema: dict) -> None:
    """Drop pydantic's per-property `title` keys in place.

    Pydantic stamps a `title` on every field ("Id", "Name", ...). json-schema-to-typescript
    turns each of those into a standalone exported type alias (Id, Id1, Title1, ...) — noise
    and name collisions. The interface NAMES we want come from the root title and the `$defs`
    keys, which we keep. So: strip every `title` that sits inside a `properties` map.
    """
    props = schema.get("properties")
    if isinstance(props, dict):
        for field_schema in props.values():
            if isinstance(field_schema, dict):
                field_schema.pop("title", None)
                _prune_property_titles(field_schema)
    for key in ("items", "additionalProperties"):
        if isinstance(schema.get(key), dict):
            _prune_property_titles(schema[key])
    for branch_key in ("anyOf", "oneOf", "allOf"):
        for branch in schema.get(branch_key, []) or []:
            if isinstance(branch, dict):
                branch.pop("title", None)
                _prune_property_titles(branch)


def build_schema() -> dict:
    """The canonical snapshot schema, generated from the pydantic source of truth."""
    from state_aggregator.types import FleetState

    schema = FleetState.model_json_schema()
    _prune_property_titles(schema)
    for def_schema in schema.get("$defs", {}).values():
        _prune_property_titles(def_schema)
    # Stable identity so the artifact is self-describing and diffs are meaningful.
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = "https://chad-fleet/hub-contracts/snapshot.schema.json"
    return schema


def serialize(schema: dict) -> str:
    # sort_keys => deterministic output so the drift guard compares cleanly.
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def write_schema() -> str:
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    text = serialize(build_schema())
    SCHEMA_PATH.write_text(text)
    return text


def _json2ts() -> Path | None:
    bin_path = HERE / "node_modules" / ".bin" / "json2ts"
    return bin_path if bin_path.exists() else None


def _run_json2ts(json2ts: Path, schema: Path, ts_out: Path, source_note: str) -> None:
    ts_out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            str(json2ts),
            "--input", str(schema),
            "--output", str(ts_out),
            "--bannerComment",
            f"/* GENERATED by packages/hub-contracts/codegen.py — DO NOT EDIT. {source_note} */",
            "--additionalProperties", "false",
        ],
        check=True,
    )


def write_ts() -> bool:
    """Generate TS for the snapshot + hand-authored schemas. False if json2ts is unavailable."""
    json2ts = _json2ts()
    if json2ts is None:
        print(
            f"[codegen] json2ts not found — run `npm install` in {HERE} first, then re-run. "
            f"Schemas were still written.",
            file=sys.stderr,
        )
        return False
    _run_json2ts(json2ts, SCHEMA_PATH, TS_PATH, "Source of truth: state_aggregator.types (pydantic).")
    for schema in HANDWRITTEN_SCHEMAS:
        ts_out = HERE / "ts" / (schema.stem.replace(".schema", "") + ".ts")
        _run_json2ts(json2ts, schema, ts_out, f"Source of truth: {schema.name} (hand-authored).")
    return True


def main() -> int:
    write_schema()
    print(f"[codegen] wrote {SCHEMA_PATH.relative_to(HERE.parent.parent)}")
    if write_ts():
        print(f"[codegen] wrote {TS_PATH.relative_to(HERE.parent.parent)} + hand-authored TS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
