/* GENERATED by packages/hub-contracts/codegen.py — DO NOT EDIT. Source of truth: admiral-chat.schema.json (hand-authored). */

/**
 * The chat contract between the dashboard and the admiral. This pins the SUBSET of the OpenAI chat-completions shape the hub relies on. It is hand-authored (not pydantic-generated like snapshot.schema.json) because the source of truth is an external standard, not our own model.
 */
export interface AdmiralChat {
  request?: ChatRequest;
  chunk?: ChatCompletionChunk;
}
/**
 * Dashboard -> /api/admiral -> admiral :8901.
 */
export interface ChatRequest {
  model?: string;
  stream?: boolean;
  messages: ChatMessage[];
  [k: string]: unknown;
}
export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}
/**
 * One SSE `data:` frame streamed back from the admiral.
 */
export interface ChatCompletionChunk {
  choices: ChatChoice[];
  [k: string]: unknown;
}
export interface ChatChoice {
  delta?: ChatDelta;
  finish_reason?: string | null;
  [k: string]: unknown;
}
export interface ChatDelta {
  content?: string;
  [k: string]: unknown;
}
