/* GENERATED by packages/hub-contracts/codegen.py — DO NOT EDIT. Source of truth: state_aggregator.types (pydantic). */

export interface FleetState {
  apps: AppSnapshot[];
  email?: EmailMessage[];
  generated_at: string;
  inbox_recent: InboxItem[];
  sessions?: SessionSnapshot[];
  summary: {
    [k: string]: unknown;
  };
  tools?: ToolSnapshot[];
}
/**
 * Per-tracked-app slice of fleet state.
 */
export interface AppSnapshot {
  baseline?: {
    [k: string]: unknown;
  } | null;
  blocked_reason?: string | null;
  cadence: string;
  id: string;
  last_progress_at: string;
  metadata?: {
    [k: string]: unknown;
  };
  mode: string;
  name: string;
  obsessive_loop_runs?: {
    [k: string]: unknown;
  }[];
  owner_brand: string;
  state: string;
}
/**
 * One inbox message — read-fast list view (no body; full body via the email-mcp read tool).
 */
export interface EmailMessage {
  date?: string;
  from_?: string;
  id: string;
  snippet?: string;
  subject?: string;
  unread?: boolean;
}
export interface InboxItem {
  body: string;
  channel: string;
  severity: "info" | "warn" | "critical";
  title: string;
  ts: string;
}
/**
 * One agent session, normalized across runtimes (Claude, auto_runtime
 * captain tracks, Codex). The hub's "all my sessions" surface reads these.
 */
export interface SessionSnapshot {
  cwd?: string | null;
  id: string;
  source: string;
  status?: string | null;
  title: string;
  updated_at: string;
}
/**
 * One MCP server the operator has registered. Safe projection — names/transport/scope
 * only, never args/headers/urls/env (those carry tokens).
 */
export interface ToolSnapshot {
  detail?: string | null;
  name: string;
  source: string;
  transport: string;
}
